version:    4.5
datafile:   quadratic.dat
specstr:    x,c
likelihood: GAUSSIAN

function:
  expression: f(x, A, u, d) = A\exp(-(x-u)^2/d)
  params:
    A: { value: 0, step: -1, min: 1, max: 100 }
    u: { value: 0, step: -1, min: 0, max: 100 }
    d: { value: 1, step: -1, min: 1, max: 100 }

data: { xmin: 1, xmax: 99, ymin: 0, ymax: 0 }

search:
  livepoints: 200
  method:     SLICE_SAMPLING
  param1:     0.5
  param2:     3
  max_tries:  100
  tries_mult: 10
  num_tries:  1
  max_steps:  10000

convergence:
  method:    LIKE_ACC
  accuracy:  1.E-05
  parameter: 0.01

clustering:
  enabled:   false
  # method:    f
  # distance:  0.5
  # bandwidth: 0.2

# Legacy stuff
lr: L
npoint: 500
nwidth: 20
