name: Continuous Integration

on:
    push:
        branches: [ "experimental" ]  # This will eventually change to master
    pull_request:
        branches: [ "experimental" ]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false

            matrix:
                os: [ubuntu-latest, windows-latest]
                build_type: [Release]
                f_compiler: [gfortran, ifort]
                include:
                    - os: windows-latest
                      c_compiler: cl
                      cpp_compiler: cl
                    - os: ubuntu-latest
                      c_compiler: gcc
                      cpp_compiler: g++            
        steps:
        - uses: actions/checkout@v3

        - name: Set reusable strings
          id: strings
          shell: bash
          run: |
              echo "build-output-dir=${{github.workspace}}/build" >> "$GITHUB_OUTPUT"

        - name: Configure CMake
          run: >
              cmake -B ${{steps.strings.outputs.build-output-dir}}
              -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}
              -DCMAKE_C_COMPILER=${{matrix.c_compiler}}
              -DCMAKE_FORTRAN_COMPILER=${{matrix.f_compiler}}
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
              -S ${{github.workspace}}

        - name: Build
          run: cmake --build ${{steps.strings.outputs.build-output-dir}} --config ${{matrix.build_type}}

